### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by AlexKR** [pinguinjkeke/php-class-tree#1]
[Enter steps to reproduce below:]

1. Open PHP file
2. Toggle on PHP Class Tree
3. Close file
4. PHP Class Tree still shown
5. Click on item in PHP Class tree

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [php-class-tree](https://github.com/pinguinjkeke/php-class-tree) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setCursorBufferPosition' of undefined

```
At /Users/AlexKR/.atom/packages/php-class-tree/lib/views/class-view.js:176

TypeError: Cannot read property 'setCursorBufferPosition' of undefined
  at ClassView.module.exports.ClassView.setLine (/Users/AlexKR/.atom/packages/php-class-tree/lib/views/class-view.js:176:9)
  at space-pen-li.<anonymous> (/Users/AlexKR/.atom/packages/php-class-tree/lib/views/class-view.js:88:9)
  at space-pen-li.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-li.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  3x -3:51.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:50.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:19.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:19.6.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -3:16.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:14.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:12.2.0 core:close (div.settings-view.pane-item)
     -3:11.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:21.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -2:21.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  4x -2:18.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:16.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:51.7.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:08.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:07.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "goto",
      "atom-ctags",
      "atom-beautifier",
      "php-getters-setters",
      "atom-beautifier",
      "atom-beautifier",
      "atom-beautifier",
      "atom-beautifier",
      "php-getters-setters",
      "php-getters-setters",
      "php-getters-setters",
      "php-getters-setters",
      "node-resolver",
      "filetype-color"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.17.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-python, v0.4.1
color-picker, v2.0.4
editorconfig, v1.0.0
file-icons, v1.5.7
file-type-icons, v0.6.0
git-tab-status, v1.9.2
javascript-snippets, v1.0.0
jsonlint, v1.1.2
language-dotenv, v1.0.0
linter, v0.12.6
linter-jshint, v0.1.6
linter-php, v0.0.15
minimap, v4.9.4
minimap-git-diff, v4.1.3
php-class-tree, v0.2.0
pretty-json, v0.3.3
raml, v0.1.0

# Dev
No dev packages
```

**Comment by pinguinjkeke** [comment]
Thank you for your response.
I need to use open/close/switch editor tabs events. onDidChangeActivePaneItem?

**Comment by pinguinjkeke** [comment]
Fixed in 1.0.0.
Now package creates a tree for every php file. For other files no tree displayed so you can't navigate into nothing.
Also added events. When you switching to another file it's tree dissapears

**Comment by e5an** [comment]
Got this error on double click. I guess what I had expected to happen was to be taken to the property declaration in the editor view.

**Comment by nnjpp** [comment]
@pinguinjkeke This error still occurs when switching from a PHP file to the settings tab. The tree is still displayed and clicking on anything in it causes this.
